[package]
name = "solo2-gui"
version = "0.0.1"
edition = "2024"

[dependencies]
libcosmic = { git = "https://github.com/pop-os/libcosmic.git" }
iced = { version = "0.13.1", features = ["tokio"] }
solo = "0.0.1"
solo2 = "0.2.2"

[profile.release]
lto = "thin"
